### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by SingleKey** [ruedigergad/clj-net-pcap#26]
I want to compile the program myself, but the code is very confusing, which makes me unable to start. Please help me

**Comment by ruedigergad** [comment]
Hi,

thanks a lot for your interest in clj-net-pcap.

Coincidentally, I had prepared an updated release some time ago and now finally managed to push it.
Please try if clj-net-pcap 1.8.1 (either uberjar from dist or the version from clojars) works for you.

Unfortunately, the manual build process, especially for the native libraries, is a bit complicated and it should be a bit better documented from me.
Improving the build documentation is on my todo list but, to be honest, I am not sure when I will find time to do this.

I hope the answer is helpful.

Cheers,
Ruediger

**Comment by ruedigergad** [comment]
PS:
Just in case, I just double checked the class file versions of the *.class files in the dist/clj-net-pcap-1.8.2-standalone.jar file and the highest major version, I see, is 53, which corresponds to Java 9:


```
~/r/p/c/clj-net-pcap (master=) rm -rf tmp
~/r/p/c/clj-net-pcap (master=) mkdir tmp
~/r/p/c/clj-net-pcap (master=) unzip dist/clj-net-pcap-1.8.2-standalone.jar -d tmp &> /dev/null
~/r/p/c/clj-net-pcap (master=) find tmp/ -iname "*.class" | xargs javap -verbose | grep "major version:" | sort | uniq -c
    142   major version: 49
   6696   major version: 52
    396   major version: 53
```

If something is still not working, please let me know.

Cheers,

Ruediger

**Comment by ruedigergad** [comment]
Ok, thanks for the feedback.
I wish you all the best for your project!
